services:
  app:
    build: .
    container_name: booking-app-be
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=booking_app_database
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - SERVER_PORT=6789
      - JWT_SECRET=k23bjwtsecret_production_change_me
    ports:
      - "6789:6789"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: booking-db
    restart: always
    environment:
      - MYSQL_DATABASE=booking_app_database
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
